name: milton-maps
channels:
  - conda-forge
dependencies:
  - dvc
  - dvc-gdrive
  - docopt
  - fiona
  - folium
  - gdal
  - geopandas
  - ipykernel
  - ipython
  - ipywidgets
  - jupyter
  - nbconvert
  - nbsphinx
  - matplotlib
  - numpy
  - pandas
  - pandas-profiling
  - pygeos
  - scikit-learn
  - scipy
  - seaborn
  - sphinx
  - typing
