name: Build and Deploy Documentation
on:
    push:
        branches: [main]
    workflow_dispatch:
permissions:
    contents: write

jobs:
    build-and-deploy:
        concurrency: ci-${{ github.ref }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up Python 3.10
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"

            - name: Install pandoc
              run: |
                sudo apt-get update
                sudo apt-get install -y pandoc

            - name: Install and configure Poetry
              uses: snok/install-poetry@v1
              with:
                version: 1.5.1
                virtualenvs-create: true
                installer-parallel: true

            - name: Install dependencies
              run: |
                make environment

            - name: Build Documentation
              run: |
                make docs

            - name: Commit documentation to gh-pages branch
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                folder: docs/_build/html
                branch: gh-pages
